[weeks]

[weeks.relations]
key = "relations"
title = "From Lexical Relations to Lexical Resources"
date = "01-12"

[weeks.wordnets]
key = "wordnets"
title = "Multilingual WordNets and Lexical Structure"
date = "01-13"


[weeks.distributions]
key = "distributions"
title = "Corpus and Distributional Evidence for Senses"
date = "01-14"


[weeks.multilingual]
key = "multilingual"
title = "Metaphor and Meaning"
date = "01-15"



[weeks.applications]
key = "applications"
title = "Evaluation, Applications, and Language Maintenance"
date = "01-16"



[weeks.schultink]
key = "schultink"
title = "Schultink Lecture"
date = "01-15"
other = "16:30, room HG-0A200"

