[weeks]

[weeks.relations]
key = "relations"
title = "Word Meanings and Wordnets"
date = "01-12"

[weeks.wordnets]
key = "wordnets"
title = "Multilingual WordNets and Lexical Structure"
date = "01-13"


[weeks.multilingual]
key = "multilingual"
title = "Metaphor and Meaning"
date = "01-14"


[weeks.distributions]
key = "distributions"
title = "Distributional Representations"
date = "01-15"


[weeks.applications]
key = "applications"
title = "Language Maintenance and Low Resource Languages"
date = "01-16"



[weeks.schultink]
key = "schultink"
title = "Schultink Lecture"
date = "01-15"
other = "16:30, room HG-0A200"

